# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "50 11 * * *"
  displayName: Daily run
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  persistCredentials: true

- script: |
    python3 arcane.py > `date +%Y-%m-%d`.txt
    git add `date +%Y-%m-%d`.txt
    git commit -m "Today's commit"
    git push origin master
  displayName: 'Pushing to git'
