trigger: none
pr: none

schedules:
- cron: "50 11 * * *"
  displayName: Daily run
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email "woof@aria.dog"
    git config --global user.name "Aria Salvatrice"
    git checkout master
    node arcane.js > ./v1/`date +%Y-%m-%d`.json
    git add ./v1/`date +%Y-%m-%d`.json
    git commit -m "Today's fortune ★"
    git push origin master
  displayName: 'Pronouncing an oracle'
