schedules:
- cron: "50 11 * * *"
  displayName: Daily run
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    python3 arcane.py > `date +%Y-%m-%d`.txt
    git config --global user.email "woof@aria.dog"
    git config --global user.name "Aria Salvatrice"
    git checkout master
    git add `date +%Y-%m-%d`.txt
    git commit -m "Today's commit"
    git push origin master
  displayName: 'Pushing to git'
