# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "50 11 * * *"
  displayName: Testing a thing!!
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python3 arcane.py > daily.txt
    git config --global user.email "woof@aria.dog"
    git config --global user.name "Aria Salvatrice"
    git config -l
    git checkout master
    git add daily.txt
    git commit -m "Trying to commit a thing from script"
    git -c credential.helper='!f() { echo "username=token"; echo "password=$GITHUBPAT"; };f' push $(tag)
    git push origin master
  displayName: 'Pushing to git'
