# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "50 11 * * *"
  displayName: Testing a thing!!
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python3 arcane.py > test.txt
    git config --global user.email "woof@aria.dog"
    git config --global user.name "Aria Salvatrice"
    git remote add origin https://github.com/AriaSalvatrice/Arcane.git
    git add test.txt
    git commit -m "Trying to commit a thing from script"
    git push origin master
  displayName: 'Pushing to git'
